name: CI
on:   
  - pull_request
  - push  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
    -  name: set env variable
       run: echo $ACTIONS_ALLOW_UNSECURE_COMMANDS
       env: 
         ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: start minikube 
      id: minikube
      uses: medyagh/setup-minikube@master
    # now you can run kubectl to see the pods in the cluster
    - name: kubectl 
      run: kubectl get pods -A
